spring:
  cloud:
    stream:
      function:
        definition: auctionSupplier;auctionBidSupplier;auctionFlushSupplier;
        bindings:
          auctionSupplier-out-0: auction-supplier
          auctionBidSupplier-out-0: auction-bid-supplier
          auctionFlushSupplier-out-0: auction-flush-supplier

      bindings:
        auction-supplier:
          destination: "auction-topic"
          producer:
            partitionKeyExpression: payload.auctionId
            partitionCount: 3
          binder: kafka

        auction-bid-supplier:
          destination: "auction-bid-topic"
          producer:
            partitionKeyExpression: payload.auctionId
            partitionCount: 3
          binder: kafka

        auction-flush-supplier:
          destination: "auction-flush-topic"
          producer:
            partitionKeyExpression: payload.auctionId
            partitionCount: 3
          binder: kafka

      kafka:
        bindings:
          auction-supplier:
            producer:
              batchTimeout: 50
              bufferSize: 10485760
              compression: zstd
          auction-bid-supplier:
            producer:
              batchTimeout: 50
              bufferSize: 10485760
              compression: zstd
          auction-flush-supplier:
            producer:
              batchTimeout: 50
              bufferSize: 10485760
              compression: zstd

        binder:
          brokers:
            - localhost:9094
            - localhost:9095
            - localhost:9096
          auto-create-topics: false
          configuration:
            security.protocol: "PLAINTEXT"

logging:
  level:
    root: INFO
    # too much logging kills performance
    # org.apache.kafka: DEBUG
    # org.springframework.cloud: DEBUG


