spring:
  cloud:
    stream:
      function:
        bindings:
          auctionSupplier-out-0: auction-supplier
          auctionBidSupplier-out-0: auction-bid-supplier

      bindings:
        auction-supplier:
          destination: "auction-topic"
          producer:
            partitionKeyExtractorName: payload.auctionId
            partitionCount: 3
          binder: kafka

        auction-bid-supplier:
          destination: "auction-bid-topic"
          producer:
            partitionKeyExtractorName: payload.auctionId
            partitionCount: 3
          binder: kafka

      kafka:
        binder:
          brokers:
            - localhost:9092
            - localhost:9093
            - localhost:9094
          auto-create-topics: false


