spring:
  cloud:
    stream:
      function:
        bindings:
          auctionSupplier-out-0: auction-supplier
          auctionBidSupplier-out-0: auction-bid-supplier

      bindings:
        auction-supplier:
          destination: "auction-topic"
          producer:
            partitionKeyExtractorName: payload.auctionId
            partitionCount: 3


        auction-bid-supplier:
          destination: "auction-bid-topic"
          producer:
            partitionKeyExtractorName: payload.auctionId
            partitionCount: 3


